### ISSUE TITLE
yarn start can't run on node ver18

### ISSUE THREAD

**Issue by linyc0817** [CAMPUS-NYCU/SmartCampus#189]
## **Describe the bug**
ERROR Log：
**err_ossl_evp_unsupported**
<img width="768" alt="webpack_node18_errorLog" src="https://github.com/CAMPUS-NYCU/SmartCampus/assets/32840701/715a6393-e4fb-4c44-9b2d-001894b8a823">

原因：
node 升級到 17,18 後會有 openssl 不支援的情況發生
[[參考](https://weekendprojects.dev/posts/fixed-node-err_ossl_evp_unsupported/#2-upgrade-your-webpack-version-to-v5540)]

解法：
1. workaround -> 用 openssl-legacy-provider
<img width="635" alt="截圖 2023-05-11 下午10 17 57" src="https://github.com/CAMPUS-NYCU/SmartCampus/assets/32840701/182761ce-55dc-4113-9535-181b118e1c38">

2. Webpack hash function 要改成 openssl 新版支援的 -> 設定 webpack hash function
3. CRA 改成 vite

**Comment by y-c-wang** [comment]
感謝:)
我應該會先考慮 CRA 改成 Vite 的選項，因為移到 Vite 也可以省下很多時間跟開發成本~

**Comment by linyc0817** [comment]
用開新專案測試過後
1. CRA (yarn create react-app)
    node 14, 18 情形下執行 yarn start 皆是可行的
2. Vite (yarn create vite)
    node 18 下執行 yarn run dev 是可行的，node 14 會出錯

Error log ----
<img width="1107" alt="截圖 2023-05-15 上午12 15 50" src="https://github.com/CAMPUS-NYCU/SmartCampus/assets/32840701/d9fc8b2e-bbaa-49d0-8fad-98c99cb39a44">

**Comment by y-c-wang** [comment]
專案從 CRA 改成 Vite 囉~ (Pull Request https://github.com/CAMPUS-NYCU/SmartCampus/pull/190)

**Comment by y-c-wang** [comment]
> 用開新專案測試過後
> 
> 1. CRA (yarn create react-app)
>    node 14, 18 情形下執行 yarn start 皆是可行的
> 2. Vite (yarn create vite)
>    node 18 下執行 yarn run dev 是可行的，node 14 會出錯
> 
> Error log ---- <img alt="截圖 2023-05-15 上午12 15 50" width="1107" src="https://user-images.githubusercontent.com/32840701/238197808-d9fc8b2e-bbaa-49d0-8fad-98c99cb39a44.png">

哦哦因為 vite 不支援舊版的 node 哦~ 不過 deployment 我都更新到 node v18 了:)
