### ISSUE TITLE
樓層沒顯示

### ISSUE THREAD

**Issue by linyc0817** [CAMPUS-NYCU/SmartCampus#28]
## **Describe the bug**
問題任務的樓層沒有顯示喔

## **Steps To Reproduce**
1. Go to 'HomePage'
2. Click on '+'
3. Fill the Mission Info and choose the 6 floor
4. Report Success
5. Click on 'Mission Icon'
6. See error

## **Expected behavior**
樓層應該要出現在地點旁邊

## **Screenshots**
<img width="1680" alt="截圖 2021-03-10 上午10 35 28" src="https://user-images.githubusercontent.com/32840701/110567735-f1f98c00-818c-11eb-8182-bfa143abc386.png">

## **Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [88.0.4324.192]

**Comment by KalleChen** [comment]
This issue has already been fixed with #21
